pipeline:
  name: Pipeline From Template
  identifier: Pipeline_From_Template
  projectIdentifier: Naman_Test
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: Stage_Template_remote
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: env
                infrastructureDefinitions:
                  - identifier: k8s_infra
              service:
                serviceRef: k8s_service
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: ""
                          sources: ""
