pipeline:
  name: SSH Test pipeline
  identifier: SSH_Test_pipeline
  projectIdentifier: DoNotDelete_NamanTest
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: ssh_s3_service
            serviceInputs:
              serviceDefinition:
                type: Ssh
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: env
            deployToAll: false
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - stepGroup:
                  name: Phase
                  identifier: Phase
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                      maxConcurrency: 1
                      partitionSize: 1
                      unit: Count
                  steps:
                    - stepGroup:
                        name: Phase Group
                        identifier: phase_group
                        strategy:
                          repeat:
                            items: <+repeat.partition>
                        steps:
                          - step:
                              name: Deploy
                              identifier: Deploy
                              timeout: 10m
                              template:
                                templateRef: account.Default_Install_Jar_Bash
                                templateInputs:
                                  type: Command
                                  spec:
                                    environmentVariables:
                                      - name: DestinationDirectory
                                        type: String
                                        value: $HOME/<+service.name>/<+env.name>
                                      - name: WorkingDirectory
                                        type: String
                                        value: $HOME/<+service.name>/<+env.name>/tomcat/bin
            rollbackSteps:
              - stepGroup:
                  name: Phase
                  identifier: Phase
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                      maxConcurrency: 1
                      partitionSize: 1
                      unit: Count
                  steps:
                    - stepGroup:
                        name: Phase Group Rollback
                        identifier: phase_group_rollback
                        strategy:
                          repeat:
                            items: <+repeat.partition>
                        steps:
                          - step:
                              name: Rollback
                              identifier: Rollback
                              timeout: 10m
                              template:
                                templateRef: account.Default_Install_Jar_Bash
                                templateInputs:
                                  type: Command
                                  spec:
                                    environmentVariables:
                                      - name: DestinationDirectory
                                        type: String
                                        value: $HOME/<+service.name>/<+env.name>
                                      - name: WorkingDirectory
                                        type: String
                                        value: $HOME/<+service.name>/<+env.name>/tomcat/bin
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
