pipeline:
  name: test gitx issue pipeline
  identifier: test_gitx_issue_pipeline
  projectIdentifier: Naman_Test
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: latest_stage_template
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: remote_SSH_Service
                serviceInputs:
                  serviceDefinition:
                    type: Ssh
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: artifact
                          sources:
                            - identifier: artifact
                              type: ArtifactoryRegistry
                              spec:
                                artifactPath: <+input>
              environment:
                infrastructureDefinitions:
                  - identifier: SSH_Infra
